### ISSUE TITLE
Unlike unix's `ls` command, the `ls` plugin leaves at first invalid path

### ISSUE THREAD

**Issue by nil0x42** [nil0x42/phpsploit#1]
### Issue:
The ls plugin leaves at the first invalid given argument path.
In order to act like the unix's `ls` command, it will will be nice if the plugin displays
an error for each invalid path, but continue processing the following paths.

### Steps to reproduce:
```
phpsploit(127.0.0.01) >  ls /home /invalid/path /home

Listing: /home
==============

Mode  Size  Last Modified                   Name
----  ----  -------------                   ----
dr-x  4K    Thu Dec 27 08:18:47 +0000 2012  .
d---  0     Thu Jan 01 00:00:00 +0000 1970  ..
dr--  4K    Sun Jul 20 06:37:03 +0000 2014  nil

[-] ls: cannot access /invalid/path: No such file or directory.
```

**Comment by yurilaaziz** [comment]
fixed ! check the pull request !

**Comment by nil0x42** [comment]
thank you, partially fixed on commit 2c6d657b7c54f6f35b6a69b614374e9b74e01256 by  yurilaaziz

**Comment by nil0x42** [comment]
the plugin now returns 1 if at least one path couldn't be listed (commit c0de2d5bcdf379bb40adde5d12f52fe846548635)
